### ISSUE TITLE
Presente >.<

### ISSUE THREAD

**Issue by FranciscoRam** [UG-OS2016/Temario#14]
Francisco Ramirez Garnica. No sabia como mandar el mensaje anteriormente por eso hasta ahora, la tarea tampoco se bien.

**Comment by JuanCrg90** [comment]
La tarea mandamela a JuanCrg90@gmail.com rl asunto ponle 
[SO2016-1][RGF] Tarea 1.1
[SO2016-1][RGF] Tarea 1.2

Plz actualiza tu perfil con una foto tuya.

PD: Recuerda tienes hasta las 12, solo en esta ocación.
