### ISSUE TITLE
tema de mañana

### ISSUE THREAD

**Issue by franciscop1s3** [UG-OS2016/Temario#15]
mi duda es sobre el tema Evaluación y selección de sistemas de cómputo.
que tengo que exponer el dia de mañana es que no se si mi tema se refiere a como adquirir la mejor unidad de computo para un usuario, o para varios como en una empresa o cierto proyecto en equipo

**Comment by JuanCrg90** [comment]
Esto no es de esta materia. para eso esta el mail y la clave de la clase.

el tema es enfocado a la empresa.
